version: '3.8'

services:
  football-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./sports_league.sqlite:/app/sports_league.sqlite:ro  # Read-only
      - ./logs:/app/logs  # Logs persistentes
    environment:
      - ENVIRONMENT=production
      - ALLOWED_ORIGINS=https://yourdomain.com
      - LOG_LEVEL=WARNING
      - ENABLE_DOCS=false  # Desabilitar docs em produção
      - PYTHONPATH=/app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
  
  # Opcional: Nginx como proxy reverso
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # Certificados SSL
    depends_on:
      - football-api
    restart: always 